### ISSUE TITLE
「先攻初手のみ，前に2マス移動禁止」の実装

### ISSUE THREAD

**Issue by F-ridge** [bababax11/brutus-reignforcement#4]
`game/game_state.py` の `move_d_vec` をいじれば良さそう？ `GameState` の `turn` に先攻初手専用の値を割り付けて例外処理を加えるのでどうだろう

**Comment by tictaqqn** [comment]
探索木を実装するのに使いたいので、ターン数というインスタンス変数をつくって加える感じにしたい！

**Comment by tictaqqn** [comment]
よさげ！あざます！
